global using System;
global using System.Text;
global using System.Diagnostics;
global using System.Runtime.InteropServices;
global using System.ComponentModel;
global using SunamoPInvoke.PInvoke;
global using SunamoPInvoke.Args;
global using SunamoPInvoke.Enums;
global using SunamoPInvoke.Structs;
